---
# tasks file for nginx
- name: installation
  import_tasks: installation.yml
  tags: installation
  when: ansible_facts.lsb.codename  == "jammy"

- name: configuration
  import_tasks: configuration.yml
  tags: configuration
  when: ansible_facts.lsb.codename  == "jammy"